server:
  port: 8888

spring:
  cloud:
    bus:
      trace:
        enabled: true   # 设置节点状态跟踪，也可以通过网页 http://localhost:port/trace 可以看到相关发送事件的数据内容

  rabbitmq:
    host: localhost   # 登录 Rabbitmq 后台管理页面地址为：http://localhost:15672
    port: 5672
    username: guest   # 默认账户
    password: guest   # 默认密码

eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${spring.cloud.client.ipAddress}:8401/eureka,http://admin:admin@${spring.cloud.client.ipAddress}:8402/eureka,http://admin:admin@${spring.cloud.client.ipAddress}:8403/eureka
      healthcheck:
        enabled: true
